const express= require('express')
const authorController=require('../controller/authorController')
const blogController=require('../controller/blogController')
const router=express.Router()
router.post('/authors',authorController.createAuthor)
router.post('/blogs', blogController.createBlog)
router.get('/authors',authorController.getAuthor)
router.get('/blogs',blogController.getBlog)
router.put('/authors',authorController.updateAuthor)
router.delete('/authors',authorController.deleteAuthor)
router.put('/blog/:blogId',blogController.updateBlog)
router.delete('/blogs/:blogId',blogController.updateBlog)
router.delete('/blogs',blogController.deleteBlog)
module.exports=router